### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by davelab6**
State license

### CODE REVIEW

**Comment by w0rm** [comment]
@davelab6 thanks!

You linked to a license file from the camera package, that I copied because Ian hasn't published it yet. 

I copied the license file into the project root and corrected the link.

**Comment by davelab6** [comment]
@w0rm thanks for that! 

I would like to suggest removing the "Exhibit B" from the license, to make the license have its default behavior, to be GPL compatible :) 

Ie, remove https://github.com/w0rm/elm-font-dimensions/blob/master/LICENSE#L369-L373

**Comment by ianmackenzie** [comment]
@davelab6, according to my reading of [the MPL 2.0 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) (see Q25), simply having the "Exhibit B" section present in the license does not actually make the software incompatible with other licenses - that section would have to be copied and pasted into the actual source code files. My intent with using the MPL for my code was certainly not to disallow GPL compatibility, so if needed I'm open to removing that section, but it doesn't look like that's actually necessary (and if not, my preference would be to just leave the license unaltered from its original form). Thoughts?

**Comment by davelab6** [comment]
Oh, I think I misunderstood. Sorry for the noise :)

**Pull request merged**
